# Generated by Django 5.0 on 2023-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='demo_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
