# Generated by Django 5.0 on 2023-12-07 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_info', '0002_profile_demo_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='demo_link',
            new_name='social_github',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_link',
            new_name='social_linkedin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='github_link',
            new_name='social_twitter',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='insta_link',
            new_name='social_website',
        ),
        migrations.AddField(
            model_name='profile',
            name='social_youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
