# Generated by Django 5.0 on 2023-12-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_info', '0006_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
