# Generated by Django 5.0 on 2023-12-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_info', '0008_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name']},
        ),
    ]
