# Generated by Django 4.2.3 on 2023-12-01 13:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_projects', '0003_alter_projects_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('values', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('date_of_upload', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_projects.projects')),
            ],
        ),
    ]
