# Generated by Django 4.2.3 on 2023-12-01 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_projects', '0005_rename_values_review_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('date_of_upload', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='vote_ratio',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='vote_total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='tag',
            field=models.ManyToManyField(blank=True, to='user_projects.tag'),
        ),
    ]
