# Generated by Django 4.2.3 on 2023-12-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_projects', '0006_tag_projects_vote_ratio_projects_vote_total_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
