# Generated by Django 5.0 on 2023-12-13 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_projects', '0011_project_owner'),
        ('users_info', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users_info.profile'),
        ),
    ]
